@host=http://localhost:3000
###
POST {{host}}/register HTTP/1.1
content-type: application/json

{
    "fullname" : "Test",
    "email" : "z@mail.com",
    "phone" : "0210980808",
    "password" : "12345"
}

###
POST {{host}}/login HTTP/1.1
content-type: application/json

{
    "email" : "z@mail.com",
    "password" : "12345"
}

###
GET {{host}}/cities
Authorization: Bearer v2.local.dqoZFGrCrBo8xCOe3l6OIJ4G3M9gHkfuMc6bGS7gRn0f1sn0jHF9YJWHMdrUOZPCqHc6H_5BYTvuVVcTWtyee8hQuA.bnVsbA
###
GET {{host}}/city/1

###
POST {{host}}/city
content-type: application/json

{
    "city" : "Surabaya"
}